export default class QuranIndexer {
  constructor() {
    this.arrPageFirstAyah = [];
    this.arrSurahPage = [];
    this.arrSurahNamesAr = [];
    this.arrSurahNamesEn = [];
    this.arrSurahNamesTrns = [];
    this.arrSurahNumAyah = [];
  }
  getSurahNameAr(iSurah /*one-based */) {
    iSurah = this.secureIndexRange(iSurah, 114);
    if (this.arrSurahNamesAr.length == 0) this.fillArrSurahNamesAr();
    return this.arrSurahNamesAr[iSurah];
  }
  getSurahNameEn(iSurah /*one-based */) {
    iSurah = this.secureIndexRange(iSurah, 114);
    if (this.arrSurahNamesEn.length == 0) this.fillArrSurahNamesEn();
    return this.arrSurahNamesEn[iSurah];
  }
  getSurahNameTrns(iSurah /*one-based */) {
    iSurah = this.secureIndexRange(iSurah, 114);
    if (this.arrSurahNamesTrns.length == 0) this.fillArrSurahNamesTrns();
    return this.arrSurahNamesTrns[iSurah];
  }
  getSurahNumAyah(iSurah /*one-based */) {
    iSurah = this.secureIndexRange(iSurah, 114);
    if (this.arrSurahNumAyah.length == 0) this.fillArrSurahNumAyah();
    return this.arrSurahNumAyah[iSurah];
  }
  getPageFromAyah(iAyah /*global index */) {
    iAyah = this.secureIndexRange(iAyah, 6236);

    if (iAyah == 1) return 1;
    if (this.arrPageFirstAyah.length == 0) this.fillArrPageFirstAyah();
    for (var i = 2; i < this.arrPageFirstAyah.length; i++) {
      if (this.arrPageFirstAyah[i] > iAyah) {
        console.log("getPageFromAyah " + iAyah + "result is " + i);
        return i - 1;
      }
    }
    return 604;
  }
  getSurahFromPage(iPage) {
    iPage = this.secureIndexRange(iPage, this.getNumPages());
    if (this.arrSurahPage.length == 0) this.fillArrSurahPage();
    for (var i = this.arrSurahPage.length - 1; i > 0; i--) {
      if (this.arrSurahPage[i] == iPage) return i;
    }
    return -1;
  }

  getPageFromSurah(iSurah) {
    iSurah = this.secureIndexRange(iSurah, 114);
    if (this.arrSurahPage.length == 0) this.fillArrSurahPage();
    return this.arrSurahPage[iPage];
  }
  getJuzuFromPage(iPage) {
    iPage = this.secureIndexRange(iPage, this.getNumPages());

    if (iPage < 22) return 1;
    if (iPage >= 582) return 30;
    return Math.floor((iPage - 2) / 20) + 1;
  }
  getPageFromJuzu(iJuzu) {
    iJuzu = this.secureIndexRange(iJuzu, 30);
    if (iJuzu == 1) return 1;
    return 2 + (iJuzu - 1) * 20;
  }
  getNumPages() {
    return 604; // todo: read from db
  }
  secureIndexRange(iIndx, iRange) {
    while (iIndx < 1) iIndx += iRange;
    while (iIndx > iRange) iIndx -= iRange;
    return iIndx;
  }
  fillArrSurahPage() {
    this.arrSurahPage.push(-1); //one based indexes
    this.arrSurahPage.push(1);
    this.arrSurahPage.push(2);
    this.arrSurahPage.push(50);
    this.arrSurahPage.push(77);
    this.arrSurahPage.push(106);
    this.arrSurahPage.push(128);
    this.arrSurahPage.push(151);
    this.arrSurahPage.push(177);
    this.arrSurahPage.push(187);
    this.arrSurahPage.push(208);
    this.arrSurahPage.push(221);
    this.arrSurahPage.push(235);
    this.arrSurahPage.push(249);
    this.arrSurahPage.push(255);
    this.arrSurahPage.push(262);
    this.arrSurahPage.push(267);
    this.arrSurahPage.push(282);
    this.arrSurahPage.push(293);
    this.arrSurahPage.push(305);
    this.arrSurahPage.push(312);
    this.arrSurahPage.push(322);
    this.arrSurahPage.push(332);
    this.arrSurahPage.push(342);
    this.arrSurahPage.push(350);
    this.arrSurahPage.push(359);
    this.arrSurahPage.push(367);
    this.arrSurahPage.push(377);
    this.arrSurahPage.push(385);
    this.arrSurahPage.push(396);
    this.arrSurahPage.push(404);
    this.arrSurahPage.push(411);
    this.arrSurahPage.push(415);
    this.arrSurahPage.push(418);
    this.arrSurahPage.push(428);
    this.arrSurahPage.push(434);
    this.arrSurahPage.push(440);
    this.arrSurahPage.push(446);
    this.arrSurahPage.push(453);
    this.arrSurahPage.push(458);
    this.arrSurahPage.push(467);
    this.arrSurahPage.push(477);
    this.arrSurahPage.push(483);
    this.arrSurahPage.push(489);
    this.arrSurahPage.push(496);
    this.arrSurahPage.push(499);
    this.arrSurahPage.push(502);
    this.arrSurahPage.push(507);
    this.arrSurahPage.push(511);
    this.arrSurahPage.push(515);
    this.arrSurahPage.push(518);
    this.arrSurahPage.push(520);
    this.arrSurahPage.push(523);
    this.arrSurahPage.push(526);
    this.arrSurahPage.push(528);
    this.arrSurahPage.push(531);
    this.arrSurahPage.push(534);
    this.arrSurahPage.push(537);
    this.arrSurahPage.push(542);
    this.arrSurahPage.push(545);
    this.arrSurahPage.push(549);
    this.arrSurahPage.push(551);
    this.arrSurahPage.push(553);
    this.arrSurahPage.push(554);
    this.arrSurahPage.push(556);
    this.arrSurahPage.push(558);
    this.arrSurahPage.push(560);
    this.arrSurahPage.push(562);
    this.arrSurahPage.push(564);
    this.arrSurahPage.push(566);
    this.arrSurahPage.push(568);
    this.arrSurahPage.push(570);
    this.arrSurahPage.push(572);
    this.arrSurahPage.push(574);
    this.arrSurahPage.push(575);
    this.arrSurahPage.push(577);
    this.arrSurahPage.push(578);
    this.arrSurahPage.push(580);
    this.arrSurahPage.push(582);
    this.arrSurahPage.push(583);
    this.arrSurahPage.push(585);
    this.arrSurahPage.push(586);
    this.arrSurahPage.push(587);
    this.arrSurahPage.push(587);
    this.arrSurahPage.push(589);
    this.arrSurahPage.push(590);
    this.arrSurahPage.push(591);
    this.arrSurahPage.push(591);
    this.arrSurahPage.push(592);
    this.arrSurahPage.push(593);
    this.arrSurahPage.push(594);
    this.arrSurahPage.push(595);
    this.arrSurahPage.push(595);
    this.arrSurahPage.push(596);
    this.arrSurahPage.push(596);
    this.arrSurahPage.push(597);
    this.arrSurahPage.push(597);
    this.arrSurahPage.push(598);
    this.arrSurahPage.push(598);
    this.arrSurahPage.push(599);
    this.arrSurahPage.push(599);
    this.arrSurahPage.push(600);
    this.arrSurahPage.push(600);
    this.arrSurahPage.push(601);
    this.arrSurahPage.push(601);
    this.arrSurahPage.push(601);
    this.arrSurahPage.push(602);
    this.arrSurahPage.push(602);
    this.arrSurahPage.push(602);
    this.arrSurahPage.push(603);
    this.arrSurahPage.push(603);
    this.arrSurahPage.push(603);
    this.arrSurahPage.push(604);
    this.arrSurahPage.push(604);
    this.arrSurahPage.push(604);
  }
  fillArrPageFirstAyah() {
    this.arrPageFirstAyah.push(-1); //one based indexes
    this.arrPageFirstAyah.push(1);
    this.arrPageFirstAyah.push(8);
    this.arrPageFirstAyah.push(13);
    this.arrPageFirstAyah.push(24);
    this.arrPageFirstAyah.push(32);
    this.arrPageFirstAyah.push(37);
    this.arrPageFirstAyah.push(45);
    this.arrPageFirstAyah.push(56);
    this.arrPageFirstAyah.push(65);
    this.arrPageFirstAyah.push(69);
    this.arrPageFirstAyah.push(77);
    this.arrPageFirstAyah.push(84);
    this.arrPageFirstAyah.push(91);
    this.arrPageFirstAyah.push(96);
    this.arrPageFirstAyah.push(101);
    this.arrPageFirstAyah.push(109);
    this.arrPageFirstAyah.push(113);
    this.arrPageFirstAyah.push(120);
    this.arrPageFirstAyah.push(127);
    this.arrPageFirstAyah.push(134);
    this.arrPageFirstAyah.push(142);
    this.arrPageFirstAyah.push(149);
    this.arrPageFirstAyah.push(153);
    this.arrPageFirstAyah.push(161);
    this.arrPageFirstAyah.push(171);
    this.arrPageFirstAyah.push(177);
    this.arrPageFirstAyah.push(184);
    this.arrPageFirstAyah.push(189);
    this.arrPageFirstAyah.push(194);
    this.arrPageFirstAyah.push(198);
    this.arrPageFirstAyah.push(204);
    this.arrPageFirstAyah.push(210);
    this.arrPageFirstAyah.push(218);
    this.arrPageFirstAyah.push(223);
    this.arrPageFirstAyah.push(227);
    this.arrPageFirstAyah.push(232);
    this.arrPageFirstAyah.push(238);
    this.arrPageFirstAyah.push(241);
    this.arrPageFirstAyah.push(245);
    this.arrPageFirstAyah.push(253);
    this.arrPageFirstAyah.push(256);
    this.arrPageFirstAyah.push(260);
    this.arrPageFirstAyah.push(264);
    this.arrPageFirstAyah.push(267);
    this.arrPageFirstAyah.push(272);
    this.arrPageFirstAyah.push(277);
    this.arrPageFirstAyah.push(282);
    this.arrPageFirstAyah.push(289);
    this.arrPageFirstAyah.push(290);
    this.arrPageFirstAyah.push(294);
    this.arrPageFirstAyah.push(303);
    this.arrPageFirstAyah.push(309);
    this.arrPageFirstAyah.push(316);
    this.arrPageFirstAyah.push(323);
    this.arrPageFirstAyah.push(331);
    this.arrPageFirstAyah.push(339);
    this.arrPageFirstAyah.push(346);
    this.arrPageFirstAyah.push(355);
    this.arrPageFirstAyah.push(364);
    this.arrPageFirstAyah.push(371);
    this.arrPageFirstAyah.push(377);
    this.arrPageFirstAyah.push(385);
    this.arrPageFirstAyah.push(394);
    this.arrPageFirstAyah.push(402);
    this.arrPageFirstAyah.push(409);
    this.arrPageFirstAyah.push(415);
    this.arrPageFirstAyah.push(426);
    this.arrPageFirstAyah.push(434);
    this.arrPageFirstAyah.push(442);
    this.arrPageFirstAyah.push(447);
    this.arrPageFirstAyah.push(451);
    this.arrPageFirstAyah.push(459);
    this.arrPageFirstAyah.push(467);
    this.arrPageFirstAyah.push(474);
    this.arrPageFirstAyah.push(480);
    this.arrPageFirstAyah.push(488);
    this.arrPageFirstAyah.push(494);
    this.arrPageFirstAyah.push(500);
    this.arrPageFirstAyah.push(505);
    this.arrPageFirstAyah.push(508);
    this.arrPageFirstAyah.push(513);
    this.arrPageFirstAyah.push(517);
    this.arrPageFirstAyah.push(520);
    this.arrPageFirstAyah.push(527);
    this.arrPageFirstAyah.push(531);
    this.arrPageFirstAyah.push(538);
    this.arrPageFirstAyah.push(545);
    this.arrPageFirstAyah.push(553);
    this.arrPageFirstAyah.push(559);
    this.arrPageFirstAyah.push(568);
    this.arrPageFirstAyah.push(573);
    this.arrPageFirstAyah.push(580);
    this.arrPageFirstAyah.push(585);
    this.arrPageFirstAyah.push(588);
    this.arrPageFirstAyah.push(595);
    this.arrPageFirstAyah.push(599);
    this.arrPageFirstAyah.push(607);
    this.arrPageFirstAyah.push(615);
    this.arrPageFirstAyah.push(621);
    this.arrPageFirstAyah.push(628);
    this.arrPageFirstAyah.push(634);
    this.arrPageFirstAyah.push(641);
    this.arrPageFirstAyah.push(648);
    this.arrPageFirstAyah.push(656);
    this.arrPageFirstAyah.push(664);
    this.arrPageFirstAyah.push(669);
    this.arrPageFirstAyah.push(672);
    this.arrPageFirstAyah.push(675);
    this.arrPageFirstAyah.push(679);
    this.arrPageFirstAyah.push(683);
    this.arrPageFirstAyah.push(687);
    this.arrPageFirstAyah.push(693);
    this.arrPageFirstAyah.push(701);
    this.arrPageFirstAyah.push(706);
    this.arrPageFirstAyah.push(711);
    this.arrPageFirstAyah.push(715);
    this.arrPageFirstAyah.push(720);
    this.arrPageFirstAyah.push(727);
    this.arrPageFirstAyah.push(734);
    this.arrPageFirstAyah.push(740);
    this.arrPageFirstAyah.push(746);
    this.arrPageFirstAyah.push(752);
    this.arrPageFirstAyah.push(759);
    this.arrPageFirstAyah.push(765);
    this.arrPageFirstAyah.push(773);
    this.arrPageFirstAyah.push(778);
    this.arrPageFirstAyah.push(783);
    this.arrPageFirstAyah.push(790);
    this.arrPageFirstAyah.push(798);
    this.arrPageFirstAyah.push(808);
    this.arrPageFirstAyah.push(817);
    this.arrPageFirstAyah.push(825);
    this.arrPageFirstAyah.push(834);
    this.arrPageFirstAyah.push(842);
    this.arrPageFirstAyah.push(849);
    this.arrPageFirstAyah.push(858);
    this.arrPageFirstAyah.push(863);
    this.arrPageFirstAyah.push(871);
    this.arrPageFirstAyah.push(880);
    this.arrPageFirstAyah.push(884);
    this.arrPageFirstAyah.push(891);
    this.arrPageFirstAyah.push(900);
    this.arrPageFirstAyah.push(908);
    this.arrPageFirstAyah.push(914);
    this.arrPageFirstAyah.push(921);
    this.arrPageFirstAyah.push(927);
    this.arrPageFirstAyah.push(932);
    this.arrPageFirstAyah.push(936);
    this.arrPageFirstAyah.push(941);
    this.arrPageFirstAyah.push(947);
    this.arrPageFirstAyah.push(955);
    this.arrPageFirstAyah.push(966);
    this.arrPageFirstAyah.push(977);
    this.arrPageFirstAyah.push(985);
    this.arrPageFirstAyah.push(992);
    this.arrPageFirstAyah.push(998);
    this.arrPageFirstAyah.push(1006);
    this.arrPageFirstAyah.push(1012);
    this.arrPageFirstAyah.push(1022);
    this.arrPageFirstAyah.push(1028);
    this.arrPageFirstAyah.push(1036);
    this.arrPageFirstAyah.push(1042);
    this.arrPageFirstAyah.push(1050);
    this.arrPageFirstAyah.push(1059);
    this.arrPageFirstAyah.push(1075);
    this.arrPageFirstAyah.push(1085);
    this.arrPageFirstAyah.push(1092);
    this.arrPageFirstAyah.push(1098);
    this.arrPageFirstAyah.push(1104);
    this.arrPageFirstAyah.push(1110);
    this.arrPageFirstAyah.push(1114);
    this.arrPageFirstAyah.push(1118);
    this.arrPageFirstAyah.push(1125);
    this.arrPageFirstAyah.push(1133);
    this.arrPageFirstAyah.push(1142);
    this.arrPageFirstAyah.push(1150);
    this.arrPageFirstAyah.push(1161);
    this.arrPageFirstAyah.push(1169);
    this.arrPageFirstAyah.push(1177);
    this.arrPageFirstAyah.push(1186);
    this.arrPageFirstAyah.push(1194);
    this.arrPageFirstAyah.push(1201);
    this.arrPageFirstAyah.push(1206);
    this.arrPageFirstAyah.push(1213);
    this.arrPageFirstAyah.push(1222);
    this.arrPageFirstAyah.push(1230);
    this.arrPageFirstAyah.push(1236);
    this.arrPageFirstAyah.push(1242);
    this.arrPageFirstAyah.push(1249);
    this.arrPageFirstAyah.push(1256);
    this.arrPageFirstAyah.push(1262);
    this.arrPageFirstAyah.push(1267);
    this.arrPageFirstAyah.push(1272);
    this.arrPageFirstAyah.push(1276);
    this.arrPageFirstAyah.push(1283);
    this.arrPageFirstAyah.push(1290);
    this.arrPageFirstAyah.push(1297);
    this.arrPageFirstAyah.push(1304);
    this.arrPageFirstAyah.push(1308);
    this.arrPageFirstAyah.push(1315);
    this.arrPageFirstAyah.push(1322);
    this.arrPageFirstAyah.push(1329);
    this.arrPageFirstAyah.push(1335);
    this.arrPageFirstAyah.push(1342);
    this.arrPageFirstAyah.push(1347);
    this.arrPageFirstAyah.push(1353);
    this.arrPageFirstAyah.push(1358);
    this.arrPageFirstAyah.push(1365);
    this.arrPageFirstAyah.push(1371);
    this.arrPageFirstAyah.push(1379);
    this.arrPageFirstAyah.push(1385);
    this.arrPageFirstAyah.push(1390);
    this.arrPageFirstAyah.push(1398);
    this.arrPageFirstAyah.push(1407);
    this.arrPageFirstAyah.push(1418);
    this.arrPageFirstAyah.push(1426);
    this.arrPageFirstAyah.push(1435);
    this.arrPageFirstAyah.push(1443);
    this.arrPageFirstAyah.push(1453);
    this.arrPageFirstAyah.push(1462);
    this.arrPageFirstAyah.push(1471);
    this.arrPageFirstAyah.push(1479);
    this.arrPageFirstAyah.push(1486);
    this.arrPageFirstAyah.push(1493);
    this.arrPageFirstAyah.push(1502);
    this.arrPageFirstAyah.push(1511);
    this.arrPageFirstAyah.push(1519);
    this.arrPageFirstAyah.push(1527);
    this.arrPageFirstAyah.push(1536);
    this.arrPageFirstAyah.push(1545);
    this.arrPageFirstAyah.push(1555);
    this.arrPageFirstAyah.push(1562);
    this.arrPageFirstAyah.push(1571);
    this.arrPageFirstAyah.push(1582);
    this.arrPageFirstAyah.push(1591);
    this.arrPageFirstAyah.push(1601);
    this.arrPageFirstAyah.push(1611);
    this.arrPageFirstAyah.push(1619);
    this.arrPageFirstAyah.push(1627);
    this.arrPageFirstAyah.push(1634);
    this.arrPageFirstAyah.push(1640);
    this.arrPageFirstAyah.push(1649);
    this.arrPageFirstAyah.push(1660);
    this.arrPageFirstAyah.push(1666);
    this.arrPageFirstAyah.push(1675);
    this.arrPageFirstAyah.push(1683);
    this.arrPageFirstAyah.push(1692);
    this.arrPageFirstAyah.push(1700);
    this.arrPageFirstAyah.push(1708);
    this.arrPageFirstAyah.push(1713);
    this.arrPageFirstAyah.push(1721);
    this.arrPageFirstAyah.push(1726);
    this.arrPageFirstAyah.push(1736);
    this.arrPageFirstAyah.push(1742);
    this.arrPageFirstAyah.push(1750);
    this.arrPageFirstAyah.push(1756);
    this.arrPageFirstAyah.push(1761);
    this.arrPageFirstAyah.push(1769);
    this.arrPageFirstAyah.push(1775);
    this.arrPageFirstAyah.push(1784);
    this.arrPageFirstAyah.push(1793);
    this.arrPageFirstAyah.push(1803);
    this.arrPageFirstAyah.push(1818);
    this.arrPageFirstAyah.push(1834);
    this.arrPageFirstAyah.push(1854);
    this.arrPageFirstAyah.push(1873);
    this.arrPageFirstAyah.push(1893);
    this.arrPageFirstAyah.push(1908);
    this.arrPageFirstAyah.push(1916);
    this.arrPageFirstAyah.push(1928);
    this.arrPageFirstAyah.push(1936);
    this.arrPageFirstAyah.push(1944);
    this.arrPageFirstAyah.push(1956);
    this.arrPageFirstAyah.push(1966);
    this.arrPageFirstAyah.push(1974);
    this.arrPageFirstAyah.push(1981);
    this.arrPageFirstAyah.push(1989);
    this.arrPageFirstAyah.push(1995);
    this.arrPageFirstAyah.push(2004);
    this.arrPageFirstAyah.push(2012);
    this.arrPageFirstAyah.push(2020);
    this.arrPageFirstAyah.push(2030);
    this.arrPageFirstAyah.push(2037);
    this.arrPageFirstAyah.push(2047);
    this.arrPageFirstAyah.push(2057);
    this.arrPageFirstAyah.push(2068);
    this.arrPageFirstAyah.push(2079);
    this.arrPageFirstAyah.push(2088);
    this.arrPageFirstAyah.push(2096);
    this.arrPageFirstAyah.push(2105);
    this.arrPageFirstAyah.push(2116);
    this.arrPageFirstAyah.push(2126);
    this.arrPageFirstAyah.push(2134);
    this.arrPageFirstAyah.push(2145);
    this.arrPageFirstAyah.push(2156);
    this.arrPageFirstAyah.push(2161);
    this.arrPageFirstAyah.push(2168);
    this.arrPageFirstAyah.push(2175);
    this.arrPageFirstAyah.push(2186);
    this.arrPageFirstAyah.push(2194);
    this.arrPageFirstAyah.push(2202);
    this.arrPageFirstAyah.push(2215);
    this.arrPageFirstAyah.push(2224);
    this.arrPageFirstAyah.push(2238);
    this.arrPageFirstAyah.push(2251);
    this.arrPageFirstAyah.push(2262);
    this.arrPageFirstAyah.push(2276);
    this.arrPageFirstAyah.push(2289);
    this.arrPageFirstAyah.push(2302);
    this.arrPageFirstAyah.push(2315);
    this.arrPageFirstAyah.push(2327);
    this.arrPageFirstAyah.push(2346);
    this.arrPageFirstAyah.push(2361);
    this.arrPageFirstAyah.push(2386);
    this.arrPageFirstAyah.push(2400);
    this.arrPageFirstAyah.push(2413);
    this.arrPageFirstAyah.push(2425);
    this.arrPageFirstAyah.push(2436);
    this.arrPageFirstAyah.push(2447);
    this.arrPageFirstAyah.push(2462);
    this.arrPageFirstAyah.push(2474);
    this.arrPageFirstAyah.push(2484);
    this.arrPageFirstAyah.push(2494);
    this.arrPageFirstAyah.push(2508);
    this.arrPageFirstAyah.push(2519);
    this.arrPageFirstAyah.push(2528);
    this.arrPageFirstAyah.push(2541);
    this.arrPageFirstAyah.push(2556);
    this.arrPageFirstAyah.push(2565);
    this.arrPageFirstAyah.push(2574);
    this.arrPageFirstAyah.push(2585);
    this.arrPageFirstAyah.push(2596);
    this.arrPageFirstAyah.push(2601);
    this.arrPageFirstAyah.push(2611);
    this.arrPageFirstAyah.push(2619);
    this.arrPageFirstAyah.push(2626);
    this.arrPageFirstAyah.push(2634);
    this.arrPageFirstAyah.push(2642);
    this.arrPageFirstAyah.push(2651);
    this.arrPageFirstAyah.push(2660);
    this.arrPageFirstAyah.push(2668);
    this.arrPageFirstAyah.push(2674);
    this.arrPageFirstAyah.push(2691);
    this.arrPageFirstAyah.push(2701);
    this.arrPageFirstAyah.push(2716);
    this.arrPageFirstAyah.push(2733);
    this.arrPageFirstAyah.push(2748);
    this.arrPageFirstAyah.push(2763);
    this.arrPageFirstAyah.push(2778);
    this.arrPageFirstAyah.push(2792);
    this.arrPageFirstAyah.push(2802);
    this.arrPageFirstAyah.push(2812);
    this.arrPageFirstAyah.push(2819);
    this.arrPageFirstAyah.push(2823);
    this.arrPageFirstAyah.push(2828);
    this.arrPageFirstAyah.push(2835);
    this.arrPageFirstAyah.push(2845);
    this.arrPageFirstAyah.push(2850);
    this.arrPageFirstAyah.push(2853);
    this.arrPageFirstAyah.push(2858);
    this.arrPageFirstAyah.push(2867);
    this.arrPageFirstAyah.push(2876);
    this.arrPageFirstAyah.push(2888);
    this.arrPageFirstAyah.push(2899);
    this.arrPageFirstAyah.push(2911);
    this.arrPageFirstAyah.push(2923);
    this.arrPageFirstAyah.push(2933);
    this.arrPageFirstAyah.push(2952);
    this.arrPageFirstAyah.push(2972);
    this.arrPageFirstAyah.push(2993);
    this.arrPageFirstAyah.push(3016);
    this.arrPageFirstAyah.push(3044);
    this.arrPageFirstAyah.push(3069);
    this.arrPageFirstAyah.push(3092);
    this.arrPageFirstAyah.push(3116);
    this.arrPageFirstAyah.push(3139);
    this.arrPageFirstAyah.push(3160);
    this.arrPageFirstAyah.push(3173);
    this.arrPageFirstAyah.push(3182);
    this.arrPageFirstAyah.push(3195);
    this.arrPageFirstAyah.push(3204);
    this.arrPageFirstAyah.push(3215);
    this.arrPageFirstAyah.push(3223);
    this.arrPageFirstAyah.push(3236);
    this.arrPageFirstAyah.push(3248);
    this.arrPageFirstAyah.push(3258);
    this.arrPageFirstAyah.push(3266);
    this.arrPageFirstAyah.push(3274);
    this.arrPageFirstAyah.push(3281);
    this.arrPageFirstAyah.push(3288);
    this.arrPageFirstAyah.push(3296);
    this.arrPageFirstAyah.push(3303);
    this.arrPageFirstAyah.push(3312);
    this.arrPageFirstAyah.push(3323);
    this.arrPageFirstAyah.push(3330);
    this.arrPageFirstAyah.push(3337);
    this.arrPageFirstAyah.push(3347);
    this.arrPageFirstAyah.push(3355);
    this.arrPageFirstAyah.push(3364);
    this.arrPageFirstAyah.push(3371);
    this.arrPageFirstAyah.push(3379);
    this.arrPageFirstAyah.push(3386);
    this.arrPageFirstAyah.push(3393);
    this.arrPageFirstAyah.push(3404);
    this.arrPageFirstAyah.push(3415);
    this.arrPageFirstAyah.push(3425);
    this.arrPageFirstAyah.push(3434);
    this.arrPageFirstAyah.push(3442);
    this.arrPageFirstAyah.push(3451);
    this.arrPageFirstAyah.push(3460);
    this.arrPageFirstAyah.push(3470);
    this.arrPageFirstAyah.push(3481);
    this.arrPageFirstAyah.push(3489);
    this.arrPageFirstAyah.push(3498);
    this.arrPageFirstAyah.push(3504);
    this.arrPageFirstAyah.push(3515);
    this.arrPageFirstAyah.push(3524);
    this.arrPageFirstAyah.push(3534);
    this.arrPageFirstAyah.push(3540);
    this.arrPageFirstAyah.push(3549);
    this.arrPageFirstAyah.push(3556);
    this.arrPageFirstAyah.push(3564);
    this.arrPageFirstAyah.push(3569);
    this.arrPageFirstAyah.push(3577);
    this.arrPageFirstAyah.push(3584);
    this.arrPageFirstAyah.push(3588);
    this.arrPageFirstAyah.push(3596);
    this.arrPageFirstAyah.push(3607);
    this.arrPageFirstAyah.push(3614);
    this.arrPageFirstAyah.push(3621);
    this.arrPageFirstAyah.push(3629);
    this.arrPageFirstAyah.push(3638);
    this.arrPageFirstAyah.push(3646);
    this.arrPageFirstAyah.push(3655);
    this.arrPageFirstAyah.push(3664);
    this.arrPageFirstAyah.push(3672);
    this.arrPageFirstAyah.push(3679);
    this.arrPageFirstAyah.push(3691);
    this.arrPageFirstAyah.push(3699);
    this.arrPageFirstAyah.push(3705);
    this.arrPageFirstAyah.push(3718);
    this.arrPageFirstAyah.push(3733);
    this.arrPageFirstAyah.push(3746);
    this.arrPageFirstAyah.push(3760);
    this.arrPageFirstAyah.push(3776);
    this.arrPageFirstAyah.push(3789);
    this.arrPageFirstAyah.push(3813);
    this.arrPageFirstAyah.push(3840);
    this.arrPageFirstAyah.push(3865);
    this.arrPageFirstAyah.push(3891);
    this.arrPageFirstAyah.push(3915);
    this.arrPageFirstAyah.push(3942);
    this.arrPageFirstAyah.push(3971);
    this.arrPageFirstAyah.push(3987);
    this.arrPageFirstAyah.push(3997);
    this.arrPageFirstAyah.push(4013);
    this.arrPageFirstAyah.push(4032);
    this.arrPageFirstAyah.push(4054);
    this.arrPageFirstAyah.push(4064);
    this.arrPageFirstAyah.push(4069);
    this.arrPageFirstAyah.push(4080);
    this.arrPageFirstAyah.push(4090);
    this.arrPageFirstAyah.push(4099);
    this.arrPageFirstAyah.push(4106);
    this.arrPageFirstAyah.push(4115);
    this.arrPageFirstAyah.push(4126);
    this.arrPageFirstAyah.push(4133);
    this.arrPageFirstAyah.push(4141);
    this.arrPageFirstAyah.push(4150);
    this.arrPageFirstAyah.push(4159);
    this.arrPageFirstAyah.push(4167);
    this.arrPageFirstAyah.push(4174);
    this.arrPageFirstAyah.push(4183);
    this.arrPageFirstAyah.push(4192);
    this.arrPageFirstAyah.push(4200);
    this.arrPageFirstAyah.push(4211);
    this.arrPageFirstAyah.push(4219);
    this.arrPageFirstAyah.push(4230);
    this.arrPageFirstAyah.push(4239);
    this.arrPageFirstAyah.push(4248);
    this.arrPageFirstAyah.push(4257);
    this.arrPageFirstAyah.push(4265);
    this.arrPageFirstAyah.push(4273);
    this.arrPageFirstAyah.push(4283);
    this.arrPageFirstAyah.push(4288);
    this.arrPageFirstAyah.push(4295);
    this.arrPageFirstAyah.push(4304);
    this.arrPageFirstAyah.push(4317);
    this.arrPageFirstAyah.push(4324);
    this.arrPageFirstAyah.push(4336);
    this.arrPageFirstAyah.push(4348);
    this.arrPageFirstAyah.push(4359);
    this.arrPageFirstAyah.push(4373);
    this.arrPageFirstAyah.push(4386);
    this.arrPageFirstAyah.push(4399);
    this.arrPageFirstAyah.push(4415);
    this.arrPageFirstAyah.push(4433);
    this.arrPageFirstAyah.push(4454);
    this.arrPageFirstAyah.push(4474);
    this.arrPageFirstAyah.push(4487);
    this.arrPageFirstAyah.push(4496);
    this.arrPageFirstAyah.push(4506);
    this.arrPageFirstAyah.push(4516);
    this.arrPageFirstAyah.push(4525);
    this.arrPageFirstAyah.push(4531);
    this.arrPageFirstAyah.push(4539);
    this.arrPageFirstAyah.push(4546);
    this.arrPageFirstAyah.push(4557);
    this.arrPageFirstAyah.push(4565);
    this.arrPageFirstAyah.push(4575);
    this.arrPageFirstAyah.push(4584);
    this.arrPageFirstAyah.push(4593);
    this.arrPageFirstAyah.push(4599);
    this.arrPageFirstAyah.push(4607);
    this.arrPageFirstAyah.push(4612);
    this.arrPageFirstAyah.push(4617);
    this.arrPageFirstAyah.push(4624);
    this.arrPageFirstAyah.push(4631);
    this.arrPageFirstAyah.push(4646);
    this.arrPageFirstAyah.push(4666);
    this.arrPageFirstAyah.push(4682);
    this.arrPageFirstAyah.push(4706);
    this.arrPageFirstAyah.push(4727);
    this.arrPageFirstAyah.push(4750);
    this.arrPageFirstAyah.push(4767);
    this.arrPageFirstAyah.push(4785);
    this.arrPageFirstAyah.push(4811);
    this.arrPageFirstAyah.push(4829);
    this.arrPageFirstAyah.push(4853);
    this.arrPageFirstAyah.push(4874);
    this.arrPageFirstAyah.push(4896);
    this.arrPageFirstAyah.push(4918);
    this.arrPageFirstAyah.push(4942);
    this.arrPageFirstAyah.push(4969);
    this.arrPageFirstAyah.push(4996);
    this.arrPageFirstAyah.push(5030);
    this.arrPageFirstAyah.push(5056);
    this.arrPageFirstAyah.push(5079);
    this.arrPageFirstAyah.push(5087);
    this.arrPageFirstAyah.push(5094);
    this.arrPageFirstAyah.push(5100);
    this.arrPageFirstAyah.push(5105);
    this.arrPageFirstAyah.push(5111);
    this.arrPageFirstAyah.push(5116);
    this.arrPageFirstAyah.push(5126);
    this.arrPageFirstAyah.push(5130);
    this.arrPageFirstAyah.push(5136);
    this.arrPageFirstAyah.push(5143);
    this.arrPageFirstAyah.push(5151);
    this.arrPageFirstAyah.push(5156);
    this.arrPageFirstAyah.push(5162);
    this.arrPageFirstAyah.push(5169);
    this.arrPageFirstAyah.push(5178);
    this.arrPageFirstAyah.push(5186);
    this.arrPageFirstAyah.push(5193);
    this.arrPageFirstAyah.push(5200);
    this.arrPageFirstAyah.push(5209);
    this.arrPageFirstAyah.push(5218);
    this.arrPageFirstAyah.push(5223);
    this.arrPageFirstAyah.push(5230);
    this.arrPageFirstAyah.push(5237);
    this.arrPageFirstAyah.push(5242);
    this.arrPageFirstAyah.push(5254);
    this.arrPageFirstAyah.push(5268);
    this.arrPageFirstAyah.push(5287);
    this.arrPageFirstAyah.push(5314);
    this.arrPageFirstAyah.push(5332);
    this.arrPageFirstAyah.push(5358);
    this.arrPageFirstAyah.push(5386);
    this.arrPageFirstAyah.push(5415);
    this.arrPageFirstAyah.push(5430);
    this.arrPageFirstAyah.push(5448);
    this.arrPageFirstAyah.push(5461);
    this.arrPageFirstAyah.push(5476);
    this.arrPageFirstAyah.push(5495);
    this.arrPageFirstAyah.push(5513);
    this.arrPageFirstAyah.push(5543);
    this.arrPageFirstAyah.push(5571);
    this.arrPageFirstAyah.push(5597);
    this.arrPageFirstAyah.push(5617);
    this.arrPageFirstAyah.push(5642);
    this.arrPageFirstAyah.push(5673);
    this.arrPageFirstAyah.push(5703);
    this.arrPageFirstAyah.push(5728);
    this.arrPageFirstAyah.push(5759);
    this.arrPageFirstAyah.push(5801);
    this.arrPageFirstAyah.push(5830);
    this.arrPageFirstAyah.push(5855);
    this.arrPageFirstAyah.push(5883);
    this.arrPageFirstAyah.push(5910);
    this.arrPageFirstAyah.push(5932);
    this.arrPageFirstAyah.push(5964);
    this.arrPageFirstAyah.push(5994);
    this.arrPageFirstAyah.push(6017);
    this.arrPageFirstAyah.push(6044);
    this.arrPageFirstAyah.push(6073);
    this.arrPageFirstAyah.push(6099);
    this.arrPageFirstAyah.push(6126);
    this.arrPageFirstAyah.push(6138);
    this.arrPageFirstAyah.push(6156);
    this.arrPageFirstAyah.push(6177);
    this.arrPageFirstAyah.push(6194);
    this.arrPageFirstAyah.push(6208);
    this.arrPageFirstAyah.push(6222);
  }
  fillArrSurahNamesAr() {
    this.arrSurahNamesAr.push("");
    this.arrSurahNamesAr.push("الفاتحة");
    this.arrSurahNamesAr.push("البقرة");
    this.arrSurahNamesAr.push("آل عمران");
    this.arrSurahNamesAr.push("النساء");
    this.arrSurahNamesAr.push("المائدة");
    this.arrSurahNamesAr.push("الأنعام");
    this.arrSurahNamesAr.push("الأعراف");
    this.arrSurahNamesAr.push("الأنفال");
    this.arrSurahNamesAr.push("التوبة");
    this.arrSurahNamesAr.push("يونس");
    this.arrSurahNamesAr.push("هود");
    this.arrSurahNamesAr.push("يوسف");
    this.arrSurahNamesAr.push("الرعد");
    this.arrSurahNamesAr.push("ابراهيم");
    this.arrSurahNamesAr.push("الحجر");
    this.arrSurahNamesAr.push("النحل");
    this.arrSurahNamesAr.push("الإسراء");
    this.arrSurahNamesAr.push("الكهف");
    this.arrSurahNamesAr.push("مريم");
    this.arrSurahNamesAr.push("طه");
    this.arrSurahNamesAr.push("الأنبياء");
    this.arrSurahNamesAr.push("الحج");
    this.arrSurahNamesAr.push("المؤمنون");
    this.arrSurahNamesAr.push("النور");
    this.arrSurahNamesAr.push("الفرقان");
    this.arrSurahNamesAr.push("الشعراء");
    this.arrSurahNamesAr.push("النمل");
    this.arrSurahNamesAr.push("القصص");
    this.arrSurahNamesAr.push("العنكبوت");
    this.arrSurahNamesAr.push("الروم");
    this.arrSurahNamesAr.push("لقمان");
    this.arrSurahNamesAr.push("السجدة");
    this.arrSurahNamesAr.push("الأحزاب");
    this.arrSurahNamesAr.push("سبإ");
    this.arrSurahNamesAr.push("فاطر");
    this.arrSurahNamesAr.push("يس");
    this.arrSurahNamesAr.push("الصافات");
    this.arrSurahNamesAr.push("ص");
    this.arrSurahNamesAr.push("الزمر");
    this.arrSurahNamesAr.push("غافر");
    this.arrSurahNamesAr.push("فصلت");
    this.arrSurahNamesAr.push("الشورى");
    this.arrSurahNamesAr.push("الزخرف");
    this.arrSurahNamesAr.push("الدخان");
    this.arrSurahNamesAr.push("الجاثية");
    this.arrSurahNamesAr.push("الأحقاف");
    this.arrSurahNamesAr.push("محمد");
    this.arrSurahNamesAr.push("الفتح");
    this.arrSurahNamesAr.push("الحجرات");
    this.arrSurahNamesAr.push("ق");
    this.arrSurahNamesAr.push("الذاريات");
    this.arrSurahNamesAr.push("الطور");
    this.arrSurahNamesAr.push("النجم");
    this.arrSurahNamesAr.push("القمر");
    this.arrSurahNamesAr.push("الرحمن");
    this.arrSurahNamesAr.push("الواقعة");
    this.arrSurahNamesAr.push("الحديد");
    this.arrSurahNamesAr.push("المجادلة");
    this.arrSurahNamesAr.push("الحشر");
    this.arrSurahNamesAr.push("الممتحنة");
    this.arrSurahNamesAr.push("الصف");
    this.arrSurahNamesAr.push("الجمعة");
    this.arrSurahNamesAr.push("المنافقون");
    this.arrSurahNamesAr.push("التغابن");
    this.arrSurahNamesAr.push("الطلاق");
    this.arrSurahNamesAr.push("التحريم");
    this.arrSurahNamesAr.push("الملك");
    this.arrSurahNamesAr.push("القلم");
    this.arrSurahNamesAr.push("الحاقة");
    this.arrSurahNamesAr.push("المعارج");
    this.arrSurahNamesAr.push("نوح");
    this.arrSurahNamesAr.push("الجن");
    this.arrSurahNamesAr.push("المزمل");
    this.arrSurahNamesAr.push("المدثر");
    this.arrSurahNamesAr.push("القيامة");
    this.arrSurahNamesAr.push("الانسان");
    this.arrSurahNamesAr.push("المرسلات");
    this.arrSurahNamesAr.push("النبإ");
    this.arrSurahNamesAr.push("النازعات");
    this.arrSurahNamesAr.push("عبس");
    this.arrSurahNamesAr.push("التكوير");
    this.arrSurahNamesAr.push("الإنفطار");
    this.arrSurahNamesAr.push("المطففين");
    this.arrSurahNamesAr.push("الإنشقاق");
    this.arrSurahNamesAr.push("البروج");
    this.arrSurahNamesAr.push("الطارق");
    this.arrSurahNamesAr.push("الأعلى");
    this.arrSurahNamesAr.push("الغاشية");
    this.arrSurahNamesAr.push("الفجر");
    this.arrSurahNamesAr.push("البلد");
    this.arrSurahNamesAr.push("الشمس");
    this.arrSurahNamesAr.push("الليل");
    this.arrSurahNamesAr.push("الضحى");
    this.arrSurahNamesAr.push("الشرح");
    this.arrSurahNamesAr.push("التين");
    this.arrSurahNamesAr.push("العلق");
    this.arrSurahNamesAr.push("القدر");
    this.arrSurahNamesAr.push("البينة");
    this.arrSurahNamesAr.push("الزلزلة");
    this.arrSurahNamesAr.push("العاديات");
    this.arrSurahNamesAr.push("القارعة");
    this.arrSurahNamesAr.push("التكاثر");
    this.arrSurahNamesAr.push("العصر");
    this.arrSurahNamesAr.push("الهمزة");
    this.arrSurahNamesAr.push("الفيل");
    this.arrSurahNamesAr.push("قريش");
    this.arrSurahNamesAr.push("الماعون");
    this.arrSurahNamesAr.push("الكوثر");
    this.arrSurahNamesAr.push("الكافرون");
    this.arrSurahNamesAr.push("النصر");
    this.arrSurahNamesAr.push("المسد");
    this.arrSurahNamesAr.push("الإخلاص");
    this.arrSurahNamesAr.push("الفلق");
    this.arrSurahNamesAr.push("الناس");
  }
  fillArrSurahNamesEn() {
    this.arrSurahNamesEn.push("");
    this.arrSurahNamesEn.push("The Opening");
    this.arrSurahNamesEn.push("The Cow");
    this.arrSurahNamesEn.push("The Family of Imraan");
    this.arrSurahNamesEn.push("The Women");
    this.arrSurahNamesEn.push("The Table");
    this.arrSurahNamesEn.push("The Cattle");
    this.arrSurahNamesEn.push("The Heights");
    this.arrSurahNamesEn.push("The Spoils of War");
    this.arrSurahNamesEn.push("The Repentance");
    this.arrSurahNamesEn.push("Jonas");
    this.arrSurahNamesEn.push("Hud");
    this.arrSurahNamesEn.push("Joseph");
    this.arrSurahNamesEn.push("The Thunder");
    this.arrSurahNamesEn.push("Abraham");
    this.arrSurahNamesEn.push("The Rock");
    this.arrSurahNamesEn.push("The Bee");
    this.arrSurahNamesEn.push("The Night Journey");
    this.arrSurahNamesEn.push("The Cave");
    this.arrSurahNamesEn.push("Mary");
    this.arrSurahNamesEn.push("Taa-Haa");
    this.arrSurahNamesEn.push("The Prophets");
    this.arrSurahNamesEn.push("The Pilgrimage");
    this.arrSurahNamesEn.push("The Believers");
    this.arrSurahNamesEn.push("The Light");
    this.arrSurahNamesEn.push("The Criterion");
    this.arrSurahNamesEn.push("The Poets");
    this.arrSurahNamesEn.push("The Ant");
    this.arrSurahNamesEn.push("The Stories");
    this.arrSurahNamesEn.push("The Spider");
    this.arrSurahNamesEn.push("The Romans");
    this.arrSurahNamesEn.push("Luqman");
    this.arrSurahNamesEn.push("The Prostration");
    this.arrSurahNamesEn.push("The Clans");
    this.arrSurahNamesEn.push("Sheba");
    this.arrSurahNamesEn.push("The Originator");
    this.arrSurahNamesEn.push("Yaseen");
    this.arrSurahNamesEn.push("Those drawn up in Ranks");
    this.arrSurahNamesEn.push("The letter Saad");
    this.arrSurahNamesEn.push("The Groups");
    this.arrSurahNamesEn.push("The Forgiver");
    this.arrSurahNamesEn.push("Explained in detail");
    this.arrSurahNamesEn.push("Consultation");
    this.arrSurahNamesEn.push("Ornaments of gold");
    this.arrSurahNamesEn.push("The Smoke");
    this.arrSurahNamesEn.push("Crouching");
    this.arrSurahNamesEn.push("The Dunes");
    this.arrSurahNamesEn.push("Muhammad");
    this.arrSurahNamesEn.push("The Victory");
    this.arrSurahNamesEn.push("The Inner Apartments");
    this.arrSurahNamesEn.push("The letter Qaaf");
    this.arrSurahNamesEn.push("The Winnowing Winds");
    this.arrSurahNamesEn.push("The Mount");
    this.arrSurahNamesEn.push("The Star");
    this.arrSurahNamesEn.push("The Moon");
    this.arrSurahNamesEn.push("The Beneficent");
    this.arrSurahNamesEn.push("The Inevitable");
    this.arrSurahNamesEn.push("The Iron");
    this.arrSurahNamesEn.push("The Pleading Woman");
    this.arrSurahNamesEn.push("The Exile");
    this.arrSurahNamesEn.push("She that is to be examined");
    this.arrSurahNamesEn.push("The Ranks");
    this.arrSurahNamesEn.push("Friday");
    this.arrSurahNamesEn.push("The Hypocrites");
    this.arrSurahNamesEn.push("Mutual Disillusion");
    this.arrSurahNamesEn.push("Divorce");
    this.arrSurahNamesEn.push("The Prohibition");
    this.arrSurahNamesEn.push("The Sovereignty");
    this.arrSurahNamesEn.push("The Pen");
    this.arrSurahNamesEn.push("The Reality");
    this.arrSurahNamesEn.push("The Ascending Stairways");
    this.arrSurahNamesEn.push("Noah");
    this.arrSurahNamesEn.push("The Jinn");
    this.arrSurahNamesEn.push("The Enshrouded One");
    this.arrSurahNamesEn.push("The Cloaked One");
    this.arrSurahNamesEn.push("The Resurrection");
    this.arrSurahNamesEn.push("Man");
    this.arrSurahNamesEn.push("The Emissaries");
    this.arrSurahNamesEn.push("The Announcement");
    this.arrSurahNamesEn.push("Those who drag forth");
    this.arrSurahNamesEn.push("He frowned");
    this.arrSurahNamesEn.push("The Overthrowing");
    this.arrSurahNamesEn.push("The Cleaving");
    this.arrSurahNamesEn.push("Defrauding");
    this.arrSurahNamesEn.push("The Splitting Open");
    this.arrSurahNamesEn.push("The Constellations");
    this.arrSurahNamesEn.push("The Morning Star");
    this.arrSurahNamesEn.push("The Most High");
    this.arrSurahNamesEn.push("The Overwhelming");
    this.arrSurahNamesEn.push("The Dawn");
    this.arrSurahNamesEn.push("The City");
    this.arrSurahNamesEn.push("The Sun");
    this.arrSurahNamesEn.push("The Night");
    this.arrSurahNamesEn.push("The Morning Hours");
    this.arrSurahNamesEn.push("The Consolation");
    this.arrSurahNamesEn.push("The Fig");
    this.arrSurahNamesEn.push("The Clot");
    this.arrSurahNamesEn.push("The Power");
    this.arrSurahNamesEn.push("The Evidence");
    this.arrSurahNamesEn.push("The Earthquake");
    this.arrSurahNamesEn.push("The Chargers");
    this.arrSurahNamesEn.push("The Calamity");
    this.arrSurahNamesEn.push("Competition");
    this.arrSurahNamesEn.push("The Declining Day");
    this.arrSurahNamesEn.push("The Traducer");
    this.arrSurahNamesEn.push("The Elephant");
    this.arrSurahNamesEn.push("Quraysh");
    this.arrSurahNamesEn.push("Almsgiving");
    this.arrSurahNamesEn.push("Abundance");
    this.arrSurahNamesEn.push("The Disbelievers");
    this.arrSurahNamesEn.push("Divine Support");
    this.arrSurahNamesEn.push("The Palm Fibre");
    this.arrSurahNamesEn.push("Sincerity");
    this.arrSurahNamesEn.push("The Dawn");
    this.arrSurahNamesEn.push("Mankind");
  }
  fillArrSurahNamesTrns() {
    this.arrSurahNamesTrns.push("");
    this.arrSurahNamesTrns.push("Al-Faatiha");
    this.arrSurahNamesTrns.push("Al-Baqara");
    this.arrSurahNamesTrns.push("Aal-i-Imraan");
    this.arrSurahNamesTrns.push("An-Nisaa");
    this.arrSurahNamesTrns.push("Al-Maaida");
    this.arrSurahNamesTrns.push("Al-An'aam");
    this.arrSurahNamesTrns.push("Al-A'raaf");
    this.arrSurahNamesTrns.push("Al-Anfaal");
    this.arrSurahNamesTrns.push("At-Tawba");
    this.arrSurahNamesTrns.push("Yunus");
    this.arrSurahNamesTrns.push("Hud");
    this.arrSurahNamesTrns.push("Yusuf");
    this.arrSurahNamesTrns.push("Ar-Ra'd");
    this.arrSurahNamesTrns.push("Ibrahim");
    this.arrSurahNamesTrns.push("Al-Hijr");
    this.arrSurahNamesTrns.push("An-Nahl");
    this.arrSurahNamesTrns.push("Al-Israa");
    this.arrSurahNamesTrns.push("Al-Kahf");
    this.arrSurahNamesTrns.push("Maryam");
    this.arrSurahNamesTrns.push("Taa-Haa");
    this.arrSurahNamesTrns.push("Al-Anbiyaa");
    this.arrSurahNamesTrns.push("Al-Hajj");
    this.arrSurahNamesTrns.push("Al-Muminoon");
    this.arrSurahNamesTrns.push("An-Noor");
    this.arrSurahNamesTrns.push("Al-Furqaan");
    this.arrSurahNamesTrns.push("Ash-Shu'araa");
    this.arrSurahNamesTrns.push("An-Naml");
    this.arrSurahNamesTrns.push("Al-Qasas");
    this.arrSurahNamesTrns.push("Al-Ankaboot");
    this.arrSurahNamesTrns.push("Ar-Room");
    this.arrSurahNamesTrns.push("Luqman");
    this.arrSurahNamesTrns.push("As-Sajda");
    this.arrSurahNamesTrns.push("Al-Ahzaab");
    this.arrSurahNamesTrns.push("Saba");
    this.arrSurahNamesTrns.push("Faatir");
    this.arrSurahNamesTrns.push("Yaseen");
    this.arrSurahNamesTrns.push("As-Saaffaat");
    this.arrSurahNamesTrns.push("Saad");
    this.arrSurahNamesTrns.push("Az-Zumar");
    this.arrSurahNamesTrns.push("Ghaafir");
    this.arrSurahNamesTrns.push("Fussilat");
    this.arrSurahNamesTrns.push("Ash-Shura");
    this.arrSurahNamesTrns.push("Az-Zukhruf");
    this.arrSurahNamesTrns.push("Ad-Dukhaan");
    this.arrSurahNamesTrns.push("Al-Jaathiya");
    this.arrSurahNamesTrns.push("Al-Ahqaf");
    this.arrSurahNamesTrns.push("Muhammad");
    this.arrSurahNamesTrns.push("Al-Fath");
    this.arrSurahNamesTrns.push("Al-Hujuraat");
    this.arrSurahNamesTrns.push("Qaaf");
    this.arrSurahNamesTrns.push("Adh-Dhaariyat");
    this.arrSurahNamesTrns.push("At-Tur");
    this.arrSurahNamesTrns.push("An-Najm");
    this.arrSurahNamesTrns.push("Al-Qamar");
    this.arrSurahNamesTrns.push("Ar-Rahmaan");
    this.arrSurahNamesTrns.push("Al-Waaqia");
    this.arrSurahNamesTrns.push("Al-Hadid");
    this.arrSurahNamesTrns.push("Al-Mujaadila");
    this.arrSurahNamesTrns.push("Al-Hashr");
    this.arrSurahNamesTrns.push("Al-Mumtahana");
    this.arrSurahNamesTrns.push("As-Saff");
    this.arrSurahNamesTrns.push("Al-Jumu'a");
    this.arrSurahNamesTrns.push("Al-Munaafiqoon");
    this.arrSurahNamesTrns.push("At-Taghaabun");
    this.arrSurahNamesTrns.push("At-Talaaq");
    this.arrSurahNamesTrns.push("At-Tahrim");
    this.arrSurahNamesTrns.push("Al-Mulk");
    this.arrSurahNamesTrns.push("Al-Qalam");
    this.arrSurahNamesTrns.push("Al-Haaqqa");
    this.arrSurahNamesTrns.push("Al-Ma'aarij");
    this.arrSurahNamesTrns.push("Nooh");
    this.arrSurahNamesTrns.push("Al-Jinn");
    this.arrSurahNamesTrns.push("Al-Muzzammil");
    this.arrSurahNamesTrns.push("Al-Muddaththir");
    this.arrSurahNamesTrns.push("Al-Qiyaama");
    this.arrSurahNamesTrns.push("Al-Insaan");
    this.arrSurahNamesTrns.push("Al-Mursalaat");
    this.arrSurahNamesTrns.push("An-Naba");
    this.arrSurahNamesTrns.push("An-Naazi'aat");
    this.arrSurahNamesTrns.push("Abasa");
    this.arrSurahNamesTrns.push("At-Takwir");
    this.arrSurahNamesTrns.push("Al-Infitaar");
    this.arrSurahNamesTrns.push("Al-Mutaffifin");
    this.arrSurahNamesTrns.push("Al-Inshiqaaq");
    this.arrSurahNamesTrns.push("Al-Burooj");
    this.arrSurahNamesTrns.push("At-Taariq");
    this.arrSurahNamesTrns.push("Al-A'laa");
    this.arrSurahNamesTrns.push("Al-Ghaashiya");
    this.arrSurahNamesTrns.push("Al-Fajr");
    this.arrSurahNamesTrns.push("Al-Balad");
    this.arrSurahNamesTrns.push("Ash-Shams");
    this.arrSurahNamesTrns.push("Al-Lail");
    this.arrSurahNamesTrns.push("Ad-Dhuhaa");
    this.arrSurahNamesTrns.push("Ash-Sharh");
    this.arrSurahNamesTrns.push("At-Tin");
    this.arrSurahNamesTrns.push("Al-Alaq");
    this.arrSurahNamesTrns.push("Al-Qadr");
    this.arrSurahNamesTrns.push("Al-Bayyina");
    this.arrSurahNamesTrns.push("Az-Zalzala");
    this.arrSurahNamesTrns.push("Al-Aadiyaat");
    this.arrSurahNamesTrns.push("Al-Qaari'a");
    this.arrSurahNamesTrns.push("At-Takaathur");
    this.arrSurahNamesTrns.push("Al-Asr");
    this.arrSurahNamesTrns.push("Al-Humaza");
    this.arrSurahNamesTrns.push("Al-Fil");
    this.arrSurahNamesTrns.push("Quraish");
    this.arrSurahNamesTrns.push("Al-Maa'un");
    this.arrSurahNamesTrns.push("Al-Kawthar");
    this.arrSurahNamesTrns.push("Al-Kaafiroon");
    this.arrSurahNamesTrns.push("An-Nasr");
    this.arrSurahNamesTrns.push("Al-Masad");
    this.arrSurahNamesTrns.push("Al-Ikhlaas");
    this.arrSurahNamesTrns.push("Al-Falaq");
    this.arrSurahNamesTrns.push("An-Naas");
  }
  fillArrSurahNumAyah() {
    this.arrSurahNumAyah.push(0);
    this.arrSurahNumAyah.push(7);
    this.arrSurahNumAyah.push(286);
    this.arrSurahNumAyah.push(200);
    this.arrSurahNumAyah.push(176);
    this.arrSurahNumAyah.push(120);
    this.arrSurahNumAyah.push(165);
    this.arrSurahNumAyah.push(206);
    this.arrSurahNumAyah.push(75);
    this.arrSurahNumAyah.push(129);
    this.arrSurahNumAyah.push(109);
    this.arrSurahNumAyah.push(123);
    this.arrSurahNumAyah.push(111);
    this.arrSurahNumAyah.push(43);
    this.arrSurahNumAyah.push(52);
    this.arrSurahNumAyah.push(99);
    this.arrSurahNumAyah.push(128);
    this.arrSurahNumAyah.push(111);
    this.arrSurahNumAyah.push(110);
    this.arrSurahNumAyah.push(98);
    this.arrSurahNumAyah.push(135);
    this.arrSurahNumAyah.push(112);
    this.arrSurahNumAyah.push(78);
    this.arrSurahNumAyah.push(118);
    this.arrSurahNumAyah.push(64);
    this.arrSurahNumAyah.push(77);
    this.arrSurahNumAyah.push(227);
    this.arrSurahNumAyah.push(93);
    this.arrSurahNumAyah.push(88);
    this.arrSurahNumAyah.push(69);
    this.arrSurahNumAyah.push(60);
    this.arrSurahNumAyah.push(34);
    this.arrSurahNumAyah.push(30);
    this.arrSurahNumAyah.push(73);
    this.arrSurahNumAyah.push(54);
    this.arrSurahNumAyah.push(45);
    this.arrSurahNumAyah.push(83);
    this.arrSurahNumAyah.push(182);
    this.arrSurahNumAyah.push(88);
    this.arrSurahNumAyah.push(75);
    this.arrSurahNumAyah.push(85);
    this.arrSurahNumAyah.push(54);
    this.arrSurahNumAyah.push(53);
    this.arrSurahNumAyah.push(89);
    this.arrSurahNumAyah.push(59);
    this.arrSurahNumAyah.push(37);
    this.arrSurahNumAyah.push(35);
    this.arrSurahNumAyah.push(38);
    this.arrSurahNumAyah.push(29);
    this.arrSurahNumAyah.push(18);
    this.arrSurahNumAyah.push(45);
    this.arrSurahNumAyah.push(60);
    this.arrSurahNumAyah.push(49);
    this.arrSurahNumAyah.push(62);
    this.arrSurahNumAyah.push(55);
    this.arrSurahNumAyah.push(78);
    this.arrSurahNumAyah.push(96);
    this.arrSurahNumAyah.push(29);
    this.arrSurahNumAyah.push(22);
    this.arrSurahNumAyah.push(24);
    this.arrSurahNumAyah.push(13);
    this.arrSurahNumAyah.push(14);
    this.arrSurahNumAyah.push(11);
    this.arrSurahNumAyah.push(11);
    this.arrSurahNumAyah.push(18);
    this.arrSurahNumAyah.push(12);
    this.arrSurahNumAyah.push(12);
    this.arrSurahNumAyah.push(30);
    this.arrSurahNumAyah.push(52);
    this.arrSurahNumAyah.push(52);
    this.arrSurahNumAyah.push(44);
    this.arrSurahNumAyah.push(28);
    this.arrSurahNumAyah.push(28);
    this.arrSurahNumAyah.push(20);
    this.arrSurahNumAyah.push(56);
    this.arrSurahNumAyah.push(40);
    this.arrSurahNumAyah.push(31);
    this.arrSurahNumAyah.push(50);
    this.arrSurahNumAyah.push(40);
    this.arrSurahNumAyah.push(46);
    this.arrSurahNumAyah.push(42);
    this.arrSurahNumAyah.push(29);
    this.arrSurahNumAyah.push(19);
    this.arrSurahNumAyah.push(36);
    this.arrSurahNumAyah.push(25);
    this.arrSurahNumAyah.push(22);
    this.arrSurahNumAyah.push(17);
    this.arrSurahNumAyah.push(19);
    this.arrSurahNumAyah.push(26);
    this.arrSurahNumAyah.push(30);
    this.arrSurahNumAyah.push(20);
    this.arrSurahNumAyah.push(15);
    this.arrSurahNumAyah.push(21);
    this.arrSurahNumAyah.push(11);
    this.arrSurahNumAyah.push(8);
    this.arrSurahNumAyah.push(8);
    this.arrSurahNumAyah.push(19);
    this.arrSurahNumAyah.push(5);
    this.arrSurahNumAyah.push(8);
    this.arrSurahNumAyah.push(8);
    this.arrSurahNumAyah.push(11);
    this.arrSurahNumAyah.push(11);
    this.arrSurahNumAyah.push(8);
    this.arrSurahNumAyah.push(3);
    this.arrSurahNumAyah.push(9);
    this.arrSurahNumAyah.push(5);
    this.arrSurahNumAyah.push(4);
    this.arrSurahNumAyah.push(7);
    this.arrSurahNumAyah.push(3);
    this.arrSurahNumAyah.push(6);
    this.arrSurahNumAyah.push(3);
    this.arrSurahNumAyah.push(5);
    this.arrSurahNumAyah.push(4);
    this.arrSurahNumAyah.push(5);
    this.arrSurahNumAyah.push(6);
  }
}
